services:
  cip-datastream-stub:
    build: ./stubs/cip-datastream-stub
    ports:
      - "8080:8080"

  upstream:
    build: ./stubs/upstream
    profiles: [local]
    ports:
      - "9090:9090"

  controller:
    image: locustio/locust
    user: ${DOCKER_UID:-1000}
    ports:
      - "8089:8089"
    environment:
      - LOCUST_HOST
      - LOCUST_HOST_HEADER
      - LOCUST_USERS
      - LOCUST_RUN_TIME
      - LOCUST_SPAWN_RATE
      - LOCUST_EXPECT_WORKERS
      - AUDIT_STUB_URL=http://cip-datastream-stub:8080
      - AUDIT_LOSS_THRESHOLD_PCT
    volumes:
      - ./:/mnt/locust
    command: --config /mnt/locust/controller.conf
    depends_on:
      - cip-datastream-stub

  worker:
    image: locustio/locust
    user: ${DOCKER_UID:-1000}
    profiles: [staging]
    environment:
      - LOCUST_HOST
      - LOCUST_HOST_HEADER
      - AUDIT_STUB_URL=http://cip-datastream-stub:8080
    volumes:
      - ./:/mnt/locust
    command: --worker -f /mnt/locust/locustfile.py --master-host controller
    depends_on:
      - controller

  worker-local:
    image: locustio/locust
    user: ${DOCKER_UID:-1000}
    profiles: [local]
    environment:
      - LOCUST_HOST
      - LOCUST_HOST_HEADER
      - AUDIT_STUB_URL=http://cip-datastream-stub:8080
    volumes:
      - ./:/mnt/locust
    command: --worker -f /mnt/locust/locustfile.py --master-host controller
    depends_on:
      - controller
      - upstream
