RESULTS_DIR ?= $(shell pwd)/results
LOCUST_HOST ?= "http://upstream:9090"
LOCUST_HOST_HEADER ?= ""
TEST_WORKERS ?= 4
LOCUST_USERS ?= 50
LOCUST_RUN_TIME ?= "1m"
LOCUST_SPAWN_RATE ?= "5"
AUDIT_LOSS_THRESHOLD_PCT ?= 1.0

test:
	mkdir -p $(RESULTS_DIR)
	@LOCUST_HOST=$(LOCUST_HOST) \
	LOCUST_HOST_HEADER=$(LOCUST_HOST_HEADER) \
	CLOUDFRONT_HEADER=$(CLOUDFRONT_HEADER) \
	LOCUST_USERS=$(LOCUST_USERS) \
	LOCUST_RUN_TIME=$(LOCUST_RUN_TIME) \
	LOCUST_SPAWN_RATE=$(LOCUST_SPAWN_RATE) \
	LOCUST_EXPECT_WORKERS=$(TEST_WORKERS) \
	AUDIT_LOSS_THRESHOLD_PCT=$(AUDIT_LOSS_THRESHOLD_PCT) \
	DOCKER_UID=`id -u` \
		docker compose --profile staging up \
		--scale worker=$(TEST_WORKERS) \
		--exit-code-from controller

test-local:
	mkdir -p $(RESULTS_DIR)
	@LOCUST_HOST=$(LOCUST_HOST) \
	LOCUST_HOST_HEADER=$(LOCUST_HOST_HEADER) \
	CLOUDFRONT_HEADER=$(CLOUDFRONT_HEADER) \
	LOCUST_USERS=$(LOCUST_USERS) \
	LOCUST_RUN_TIME=$(LOCUST_RUN_TIME) \
	LOCUST_SPAWN_RATE=$(LOCUST_SPAWN_RATE) \
	LOCUST_EXPECT_WORKERS=1 \
	AUDIT_LOSS_THRESHOLD_PCT=$(AUDIT_LOSS_THRESHOLD_PCT) \
	DOCKER_UID=`id -u` \
		docker compose --profile local up \
		--scale worker-local=1 \
		--exit-code-from controller

clean:
	DOCKER_UID=`id -u` docker compose rm -sf
	rm -rf $(RESULTS_DIR)

smoke:
	$(MAKE) test-local LOCUST_USERS=1 LOCUST_RUN_TIME=30s LOCUST_SPAWN_RATE=1

.PHONY: test test-local clean smoke
